Add another dependency causing circleCI to fail > Rocket.Chat@0.65.1 test /home/circleci/repo > node .scripts/start.js
Exception in callback of async function: Error: Cannot find module 'ee-first'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)